breezebm/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("login/", LoginView.as_view(template_name="accountapp/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

breezebm/breezebm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breezebm/profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"

urlpatterns = [
    path("create/", ProfileCreateView.as_view(), name="create"),
    path("update/<int:pk>", ProfileUpdateView.as_view(), name="update"),
]

breezebm/accountapp/models.py
from django.db import models


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

breezebm/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["username"].disabled = True

breezebm/accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld


has_ownership = [account_ownership_required, login_required]


@login_required
def hello_world(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            temp = request.POST.get("hello_world_input")

            new_hello_world = HelloWorld()
            new_hello_world.text = temp
            new_hello_world.save()

            # return render(request, "accountapp/hello_world.html", context={"hello_world_list": hello_world_list})
            return HttpResponseRedirect(reverse("accountapp:hello_world"))
        else:
            hello_world_list = HelloWorld.objects.all()
            return render(request, "accountapp/hello_world.html", context={"hello_world_list": hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    # class에서는 reverse_lazy만 사용 가능
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/create.html"


class AccountDetailView(DetailView):
    model = User
    context_object_name = "target_user"
    template_name = "accountapp/detail.html"


@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = "target_user"
    form_class = AccountUpdateForm
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/update.html"


@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy("accountapp:login")
    template_name = "accountapp/delete.html"

breezebm/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align:center; max-width:500px; margin:4rem auto">
    <!--ACCOUNT APP의 create로 요청을 보내라!-->
    <div>
        <h4 style="font-family: 'Black Han Sans', sans-serif">SIGNUP</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
<!--      {{ form }}-->
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

breezebm/accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align:center; max-width:500px; margin:4rem auto">
    <div>
        <h4 style="font-family: 'Black Han Sans', sans-serif">LEAVE THE SERVICE</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=user.pk %}" method="post">
        {% csrf_token %}
        <div class="change_text">Deleted data will not be recovered.</div>
        <input type="submit" class="btn btn-sm btn-danger rounded-pill col-3 mt-3">
    </form>
</div>

{% endblock %}

breezebm/accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}

<div>
    <div style="text-align:center; max-width:500px; margin: 4rem auto;">
        {% if target_user.profile %}
        <h2 style="font-family: NanumSquareNeoExtraBold">PROFILE</h2>

        <img src="{{ target_user.profile.image.url }}" alt="" style="height: 8rem; width: 8rem; border-radius: 10rem; margin-bottom: 1rem; margin-top: 1rem">

        <h2 style="font-family: NanumSquareNeoExtraBold">
            {{ target_user.profile.nickname }}
            {% if target_user == user %}
                <a class="change_text" style="text-decoration:none;" href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                    <div style="font-size: .5rem">
                            EDIT PROFILE
                    </div>
                </a>
        </h2>
            {% endif %}
        <h5 style="margin-top: 1.2rem; margin-bottom: 1.2rem">
            {{ target_user.profile.message }}
        </h5>
        {% else %}
            {% if target_user == user %}
                <a class="change_text" style="text-decoration:none;" href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: NanumSquareNeoExtraBold">
                        CREATE PROFILE
                </h2>
            </a>
            {% else %}
            <h2 class="change_text">
                YOU DON'T HAVE YOUR OWN NICKNAME
            </h2>
            {% endif %}
        {% endif %}

        {% if target_user == user %}
        <a style="color:grey; text-decoration:none;" href="{% url 'accountapp:update' pk=target_user.pk %}">
            <p>CHANEGE INFO</p>
        </a>
        <a style="color:grey; text-decoration:none;" href="{% url 'accountapp:delete' pk=target_user.pk %}">
            <div style="font-size: .4rem">LEAVE THIS SERVICE</div>
        </a>
        {% endif %}
    </div>
</div>


{% endblock %}

breezebm/accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center">
        <h4 style="font-family: 'Black Han Sans', sans-serif">
          HELLO WORLD LIST
        </h4>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>

            </div>
            <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3" value="POST">
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
                <div>
                    {{ hello_world.text }}
                </div>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

breezebm/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div>
        <h4 style="font-family: 'Black Han Sans', sans-serif">LOGIN</h4>
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
<!--            {{ form }}-->
            {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3">
        </form>
    </div>
</div>

{% endblock%}

breezebm/accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align:center; max-width:500px; margin:4rem auto">
    <div>
        <h4 style="font-family: 'Black Han Sans', sans-serif">CHANGE INFO</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}

        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}