breezebm/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("login/", LoginView.as_view(template_name="accountapp/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

breezebm/articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>", ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete"),
]

breezebm/breezebm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breezebm/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareNeoBold'">
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

breezebm/templates/footer.html
<div class="breeze_footer">
    <div class="breeze_footer_button">
        <span>NOTICE</span> |
        <span>SNS</span> |
        <span>CONTACT</span>
    </div>
    <div style="margin-top: 1rem">
        <h6 class="breeze_logo">COPYRIGHT © 2023 BREEZEBM. ALL RIGHTS RESERVED</h6>
    </div>
</div>

breezebm/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1", shrink-to-fit="no">
    <title>BreezeBM</title>

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">


    <!-- GOOGLE FONT LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">

    <!-- IMPORT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face{
            font-family: 'NanumSquareNeoLight';
            src: local('NanumSquareNeoLight'),
            url("{% static 'fonts/NanumSquareNeoOTF-Lt.otf'%}") format("opentype")
        }

        @font-face{
            font-family: 'NanumSquareNeo';
            src: local('NanumSquareNeo'),
            url("{% static 'fonts/NanumSquareNeoOTF-Rg.otf'%}") format("opentype")
        }

        @font-face{
            font-family: 'NanumSquareNeoBold';
            src: local('NanumSquareNeoBold'),
            url("{% static 'fonts/NanumSquareNeoOTF-Bd.otf'%}") format("opentype")
        }

        @font-face{
            font-family: 'NanumSquareNeoExtraBold';
            src: local('NanumSquareNeoExtraBold'),
            url("{% static 'fonts/NanumSquareNeoOTF-Eb.otf'%}") format("opentype")
        }
        @font-face{
            font-family: 'NanumSquareNeoHeavy';
            src: local('NanumSquareNeoHeavy'),
            url("{% static 'fonts/NanumSquareNeoOTF-Hv.otf'%}") format("opentype")
        }

        .change_text {
            animation: change_text 1s linear infinite;
        }

        @keyframes change_text {
            0% {color: black;}
            17% {color: red;}
            34% {color: orange;}
            51% {color: #FDE300;}
            68% {color: green;}
            85% {color: blue;}
            100% {color: purple;}
        }
    </style>
</head>

breezebm/templates/header.html
<div class="breeze_header">
    <div>
        <h1 class="breeze_logo">BREEZEBM</h1>
    </div>
    <div>
        <a style="color:black; text-decoration:none" href="{% url 'articleapp:list' %}">
            <span style="font-size:0.7rem">ARTICLES</span>
        </a>
        <span>NAV</span>
        <span>NAV</span>
        {% if not user.is_authenticated %}
        <!--next 로그인을 하고 나서 원래자리로 돌아오게 됨-->
        <a style="color:black; text-decoration:none" href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span style="font-size:0.7rem">LOGIN</span>
        </a>
        <a style="color:black; text-decoration:none" href="{% url 'accountapp:create' %}?next={{ request.path }}">
            <span style="font-size:0.7rem">SIGNUP</span>
        </a>
        {% else %}
        <a style="color:black; text-decoration:none" href="{% url 'accountapp:detail'  pk=user.pk %}">
            <span style="font-size:0.7rem">MYPAGE</span>
        </a>
        <a style="color:black; text-decoration:none" href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span style="font-size:0.7rem">LOGOUT</span>
        </a>
        {% endif %}
    </div>
</div>